version: '3'
services:
        web:
                build: .
                container_name: midterm_web_hslee21
                ports:
                        - 5017:5000
                volumes:
                        - ./data/animals.json:/animals.json
        redis:
                image: redis:latest
                ports:
                        - 6397:6379
                volumes:
                        - ./config/redis.conf:/redis.conf
                        - ./data:/data
                command: ["redis-server","/redis.conf"]
