---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hslee21-pvc
  labels:
      username: hslee21
      env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi

