---
apiVersion: v1
kind: Service
metadata:
  name: hslee21-test-flask
  labels:
    username: hslee21
    env: test
spec:
  type: ClusterIP
  selector:
    app: hslee21-test-flask
  ports:
  - name: hslee21-flask
    port: 5000
    targetPort: 5000
