---
apiVersion: v1
kind: Service
metadata:
  name: hslee21-test-redis
  labels:
    username: hslee21
    env: test
spec:
  type: ClusterIP
  selector:
    app: hslee21-test-redis
  ports:
  - name: hslee21-redis
    port: 6379
    targetPort: 6379
