---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hslee21-flask-deployment
  labels:
    username: hslee21
    env: test
    app: hslee21-test-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hslee21-test-flask
  template:
    metadata:
      labels:
        username: hslee21
        env: test
        app: hslee21-test-flask
    spec:
      containers:
        - name: hslee21-test-flask
          imagePullPolicy: Always
          image: hyeonseunglee/hw3 
          ports:
          - name: hslee21-flask
            containerPort: 5000
